[postgres]
type = "postgres"
host = "localhost"
port = 5432
user = "postgres"
password = "password"

# Example with database specified - skips database selection
[postgres-mydb]
type = "postgres"
host = "localhost"
port = 5432
user = "postgres"
password = "password"
database = "mydb"

[mysql]
type = "mysql"
host = "localhost"
port = 3306
user = "root"
password = "password"
readonly = true

[scylla]
type = "cassandra"
host = "localhost"
port = 9042

[clickhouse]
type = "clickhouse"
host = "localhost"
port = 8123
user = "default"
password = "password"
